### PR TITLE
Feature/nb 23 object structure

### PR DESCRIPTION
**Pull request by chrislehrter**

### CODE REVIEW

**Comment by chrislehrter** [comment]
I've made a number of changes here:

- Created a 'Transaction' interface which is implemented by 'TopUp' 'Transfer' 'directdebit' (in the future) etc.

- modified the 'addTestData' in the 'NewBank' class to create customers for each entry in the MockDB and create accounts

- modified the 'transactions' ArrayList in the account object to accept any time of transaction (not just 'topups')

- modified 'addBalance' and 'removeBalance' methods in 'NewBank' to create a 'Transfer' transaction object when called (to record movement in/out of account 

- created a skeleton 'DirectDebit' class for future implementation

**Comment by chrislehrter** [comment]
Be aware that I've made changes to 8 of the 15 files in this commit, so merging could be a challenge if there are lots of people working in parallel!!

**Comment by rturo20** [comment]
Thanks @chrislehrter.  Before we merge this pull request (feature/NB-23-ObjectStructure), should we have scrum team members confirm that they are comfortable that we do so?

**Comment by chrislehrter** [comment]
@rturo20 yes definitely

**Comment by ibrahimdirar** [comment]
Looks good to me, only addition I'd make is change the Account types and transaction statuses from Strings to Enums. Statuses and types can only be limited predefined values so this is a good use case for it.

**Comment by chrislehrter** [comment]
@ibrahimdirar I agree this would be a good addition. Would you like me to add that first or are you happy for us to merge this and make the fix in the next iteration?

**Comment by ibrahimdirar** [comment]
next iteration I'd say, getting this merged so other branches can fix conflicts sooner is better. doesn't make sense to hold up the merge for such a minor and non structural tweak

**Comment by rturo20** [comment]
Clearly this code will conflict with @ArturRomanov  pull request.  As noted by @ibrahimdirar, we should accept @chrislehrter ‘s  pull request and have other code adjusted to suit this.  @ArturRomanov @MrDmitriev are you ok with this approach?

**Comment by MrDmitriev** [comment]
> Clearly this code will conflict with @ArturRomanov pull request. As noted by @ibrahimdirar, we should accept @chrislehrter ‘s pull request and have other code adjusted to suit this. @ArturRomanov @MrDmitriev are you ok with this approach?

I agree

**Review by rturo20 — APPROVED** [review]
Approving this pull request on the basis that as agreed, the scrum team will resolve conflicts caused.

**Comment by rturo20** [comment]
As agreed I have merged the feature/NB-23-ObjectStructure into main. I am assuming the conflicts will be picked up by each of us as part of next week’s sprint.

**Comment by ArturRomanov** [comment]
I agree with the approach. I have adjusted the code for view transactions.

**Pull request merged**
