### PR TITLE
added the 'user type' attribute to MockDB and customers,

### PR DESCRIPTION
**Pull request by chrislehrter**
including ability to get and set attribute. This is tested in the 'TestMockDB' file

### CODE REVIEW

**Review by rturo20 — COMMENTED** [review]
@chrislehrter @MrDmitriev Looks good. Ideally line 101 and 104 in MockDB should be amended to rename the customer String method parameter to parameter String userName.  While this doesn't change the code functionality, it keeps the naming convention consistent.

**Comment by chrislehrter** [comment]
> 

good point, I'll change that quickly now

**Comment by chrislehrter** [comment]
done :)

**Review by rturo20 — APPROVED** [review]

**Comment by rturo20** [comment]
@chrislehrter NB-8 merged. Thank you.

**Pull request merged**
