### PR TITLE
Implemented view transactions

### PR DESCRIPTION
**Pull request by ArturRomanov**
This code allows users to view transactions.

### CODE REVIEW

**Comment by chrislehrter** [comment]
Hi @ArturRomanov, this looks good but I think there are some clashes between this and NB-23. I see that you've created a 'Transaction' class, wheras I've proposed a Transaction interface which can be implemented by 'topup', 'payment', 'transfer', 'directdebit' etc.

Also, I see you've put an arraylist of transfers in the mockDB object. I thought it would be better to put it within the 'Account' object, so that transactions are immediately linked to the account the money is being transacted to/from. This would give you a list of transactions per account, instead of a big list of overall transactions (I think this would make it easier)

**Comment by rturo20** [comment]
See comments at https://github.com/MrDmitriev/new-bank/pull/13 outlining how we propose to deal with conflict.  That is, accept https://github.com/MrDmitriev/new-bank/pull/13 and have other code under development including this pull request adjusted to suit.

**Comment by chrislehrter** [comment]
Hi @ArturRomanov, would you like me to help with merging this into the rest of the codebase?

**Review by MrDmitriev — APPROVED** [review]

**Comment by ArturRomanov** [comment]
@chrislehrter @rturo20 @MrDmitriev @ibrahimdirar @Ben04051 @ahatnamas The conflicts with the code which you mentioned have been solved and view transactions feature has been implemented.

**Pull request merged**
